# Generated by Django 4.2.2 on 2023-07-19 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_endpoints', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='weathercurrent',
            table='cityframe"."weather_current',
        ),
    ]
