# Generated by Django 4.2.2 on 2023-07-17 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_endpoints', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='weatherfc',
            table='testDB.cityframe.weather_fc',
        ),
    ]
