# Generated by Django 4.2.2 on 2023-07-19 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_endpoints', '0002_alter_weathercurrent_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weathercurrent',
            options={'managed': True},
        ),
    ]
