# Generated by Django 4.2.2 on 2023-07-17 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_endpoints', '0002_alter_weatherfc_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='weatherfc',
            table='cityframe.weather_fc',
        ),
    ]
