# Generated by Django 4.2.2 on 2023-07-17 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_endpoints', '0003_alter_weatherfc_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='weatherfc',
            table='weather_fc',
        ),
    ]
