# Generated by Django 4.2.2 on 2023-08-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_endpoints', '0006_zoning'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='zone_type',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='zone_type',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
