# Generated by Django 4.2.2 on 2023-08-08 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_endpoints', '0007_query_zone_type_response_zone_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='architecture',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
