# Generated by Django 4.2.2 on 2023-08-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_endpoints', '0008_response_architecture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zones',
            fields=[
                ('location_id', models.IntegerField(primary_key=True, serialize=False)),
                ('zone', models.CharField(max_length=100)),
                ('trees', models.IntegerField()),
                ('trees_scaled', models.IntegerField()),
                ('main_zone_style', models.CharField(max_length=100)),
                ('main_zone_style_value', models.IntegerField()),
                ('main_zone_type', models.CharField(max_length=100)),
                ('main_zone_type_value', models.IntegerField()),
            ],
            options={
                'db_table': 'cityframe"."zones',
                'managed': False,
            },
        ),
    ]
