# Generated by Django 4.2.2 on 2023-08-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_endpoints', '0009_zones'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiddenGem',
            fields=[
                ('zone_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('trees', models.IntegerField()),
                ('main_style_amount', models.IntegerField()),
                ('main_style', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cityframe"."hidden_gems',
            },
        ),
    ]
